trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - dev
    - refs/tags/v*
    exclude:
    - refs/heads/*
    - refs/remotes/*
  
jobs: 
 - job: build_all_mac
   displayName: Build all tasks (macos)
   condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
   pool:
    vmImage: 'macos-latest'
   steps:
   - task: UseNode@1
     inputs:
       checkLatest: true
   - task: Npm@1
     inputs:
       command: 'install'
       workingDir: 'web/ReactNativeBingo'
   - task: ReactNativePrepare@0
     inputs:
       platform: 'android'
       reactGradle: 'web/ReactNativeBingo/android/app/build.gradle'
       cwd: 'web/ReactNativeBingo'
   - task: ReactNativePrepare@0
     inputs:
       platform: 'ios'
       xcodeProject: 'web/ReactNativeBingo/ios/ReactNativeBingo.xcodeproj/project.pbxproj'
       cwd: 'web/ReactNativeBingo'
   - task: Gradle@2
     displayName: 'build apk with Gradle' 
     inputs:
       gradleWrapperFile: 'web/ReactNativeBingo/android/gradlew'
       workingDirectory: 'web/ReactNativeBingo/android/app'
       tasks: 'assembleRelease'
       publishJUnitResults: false
       javaHomeOption: 'JDKVersion'
       sonarQubeRunAnalysis: false
     continueOnError: false
  #  - task: GitHubReleasePublish@1
  #    displayName: 'Publish'
  #    inputs:
  #      githubEndpoint: 'wudameinv (1)'
  #      manuallySetRepository: true
  #      githubOwner: 'wudameinv'
  #      githubRepositoryName: 'aelf-boilerplate'
  #      githubReleaseDraft: true
  #      githubReleasePrerelease: true
  #      githubIgnoreAssets: false
  #      githubReleaseAsset: 'web/ReactNativeBingo/android/app/build/outputs/apk/release/app-release.apk'
  #      githubReuseRelease: true
  #      githubReuseDraftOnly: true
  #      githubSkipDuplicatedAssets: false
  #      githubEditRelease: true
  #      githubDeleteEmptyTag: true
